third.py	#wont work since .gitignore created after this one was commited 
fourth.py		#works fine! no it doesnt